### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by Tiiiger** [eaclark07/sms#1]
Hi!

I really enjoy reading your paper, _Sentence Mover’s Similarity: Automatic Evaluation for Multi-Sentence Texts_, and found it to be insightful and inspiring. Sorry to chase but I just want to ask what a timeline for the code release will be? Looking forward to experimenting with S+WMS myself. 

Bests,
Tianyi

**Comment by eaclark07** [comment]
The code should be released within the next 1-2 weeks.
Thank you for your interest and your patience!
