### ISSUE TITLE
About the Summaries Dataset

### ISSUE THREAD

**Issue by Chen-Wang-CUHK** [eaclark07/sms#4]
Hi Elizabeth,
     Thank you for your interesting work. Is it possible to share the summaries dataset that you used to get the results of Table 2 in the paper? I noted that in the raw data from Chaganty et al. (2018), there are some instances only containing one or two summary systems' human scores instead of the complete five summarization systems. How do you handle these cases? remove them or keep them? Thank you!

**Comment by eaclark07** [comment]
We only included the instances that have scores from 2 or more human judges. So you can remove any instances with fewer than 2 scores.

**Comment by Chen-Wang-CUHK** [comment]
> We only included the instances that have scores from 2 or more human judges. So you can remove any instances with fewer than 2 scores.

Dear Elizabeth, thank you for your clarification.
